apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-worker
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/pyforge-python-school-3-default: "true"
        io.kompose.service: celery-worker
    spec:
      containers:
        - args:
            - celery
            - -A
            - src.celery_worker
            - worker
            - --loglevel=info
          image: celery-worker
          name: celery-worker
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: celery-worker-claim0
      restartPolicy: Always
      volumes:
        - name: celery-worker-claim0
          persistentVolumeClaim:
            claimName: celery-worker-claim0
status: {}
