apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web1
  name: web1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/pyforge-python-school-3-default: "true"
        io.kompose.service: web1
    spec:
      containers:
        - env:
            - name: SERVER_ID
              value: SERVER-1
          image: web1
          name: web1
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /src
              name: web1-claim0
      restartPolicy: Always
      volumes:
        - name: web1-claim0
          persistentVolumeClaim:
            claimName: web1-claim0
status: {}
