name: Python static analysis
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  static-analysis-with-flake8:
    runs:
      using: 'node20'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=100 --statistics