name: Testing app with pytest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-fastapi-app-functions-using-pytest:
    runs:
      using: 'node20'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.4
      - run: python -m pip install -r requirements.txt
      - run: python -m pytest tests/