name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}        
        username: ubuntu                   
        key: ${{ secrets.SSH_KEY }}  
        port: 22                             
        script: |
          echo "Deploying to EC2..."
          cd /home/projects/python-school-3
          git pull origin main
          docker-compose down
          docker-compose up -d
